// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEgXrZox-RpnV09eo-2SAl20lsOlQH6vU',
    appId: '1:336785513468:web:c37b0becf543d99770b079',
    messagingSenderId: '336785513468',
    projectId: 'santarana-quiz',
    authDomain: 'santarana-quiz.firebaseapp.com',
    storageBucket: 'santarana-quiz.firebasestorage.app',
    measurementId: 'G-PDEXZCX8BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP4ksXYPnWL7mmIN4_Y-_9-5eQd1JrOTg',
    appId: '1:336785513468:android:032c169a52304a9770b079',
    messagingSenderId: '336785513468',
    projectId: 'santarana-quiz',
    storageBucket: 'santarana-quiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHo7cpGxZOz2Vnv9MtSQV2Q6J0e2vaATg',
    appId: '1:336785513468:ios:d9f19792d9dfe8e870b079',
    messagingSenderId: '336785513468',
    projectId: 'santarana-quiz',
    storageBucket: 'santarana-quiz.firebasestorage.app',
    iosBundleId: 'com.example.santarana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHo7cpGxZOz2Vnv9MtSQV2Q6J0e2vaATg',
    appId: '1:336785513468:ios:d9f19792d9dfe8e870b079',
    messagingSenderId: '336785513468',
    projectId: 'santarana-quiz',
    storageBucket: 'santarana-quiz.firebasestorage.app',
    iosBundleId: 'com.example.santarana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEgXrZox-RpnV09eo-2SAl20lsOlQH6vU',
    appId: '1:336785513468:web:d7c98b4011b40b9c70b079',
    messagingSenderId: '336785513468',
    projectId: 'santarana-quiz',
    authDomain: 'santarana-quiz.firebaseapp.com',
    storageBucket: 'santarana-quiz.firebasestorage.app',
    measurementId: 'G-5RKZ0EKVLZ',
  );
}
